# Generated by Django 5.2.7 on 2025-11-11 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='menu_type',
            field=models.CharField(choices=[('main', 'Main Menu'), ('footer', 'Footer Menu'), ('legal', 'Legal Menu'), ('sidebar', 'Sidebar Menu')], default='main', max_length=20),
        ),
        migrations.AddIndex(
            model_name='menuitem',
            index=models.Index(fields=['parent', 'is_active'], name='app_menuite_parent__64b3bd_idx'),
        ),
        migrations.AddIndex(
            model_name='page',
            index=models.Index(fields=['show_in_menu', 'is_active'], name='app_page_show_in_fb9583_idx'),
        ),
        migrations.AddConstraint(
            model_name='menuitem',
            constraint=models.CheckConstraint(condition=models.Q(('parent', models.F('pk')), _negated=True), name='check_parent_not_self'),
        ),
    ]
