# Generated by Django 5.2.7 on 2025-11-12 01:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_menuitem_menu_type_and_more'),
    ]

    operations = [

        migrations.AlterUniqueTogether(
            name='menuitemtranslation',
            unique_together=None,
        ),
        migrations.AlterUniqueTogether(
            name='pagetranslation',
            unique_together=None,
        ),
        migrations.DeleteModel(
            name='MenuItem',
        ),
        migrations.DeleteModel(
            name='MenuItemTranslation',
        ),
        migrations.DeleteModel(
            name='Page',
        ),
        migrations.DeleteModel(
            name='PageTranslation',
        ),
    ]
